{
    "name": "Product QR Track",
    "version": "19.0.1.0.0",
    "summary": "Adds QR code to track the customer analytics.",
    "website": "https://leofren.com",
    "author": "Leofren Technologies",
    "maintainer": "Fenil Moradiya",
    "depends": ["stock", "website_sale"],
    "data": [
        "security/ir.model.access.csv",
        "views/product_template_views.xml",
        "views/product_qr_visit_views.xml",
        "reports/product_qr_report.xml",
    ],
    "images": ["static/description/icon.png"],
    "license": "OPL-1",
    "application": True,
    "installable": True,
    "auto_install": False,
}
